name: deploy-on-k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Decode kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
          echo "✅ kubeconfig decoded"
          cat kubeconfig

      - name: Test Kubernetes connection
        run: |
          kubectl --kubeconfig=kubeconfig config view
          kubectl --kubeconfig=kubeconfig get nodes
          kubectl --kubeconfig=kubeconfig cluster-info
