name: Deploy nginx Pod via SSH Tunnel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.keyrsa }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

     
      - name: Start SSH tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -N -L 6443:10.17.3.6:6443 k8s@10.17.3.6 "kubectl get nodes"
    