name: deploy-on-k8s

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/


      - name: Test Kubernetes connection
        run: |
          echo "Testing Kubernetes connection..."
          echo {{ SECRETS.KEYRSA }} > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa -L 6443:localhost:6443 k8s@10.17.3.6 "kubectl get nodes"
          "
