name: Kubernetes Node Check

on:
  workflow_dispatch: # Permet de lancer le workflow manuellement
  push:
    branches:
      - main

jobs:
  kubectl-job:
    runs-on: ubuntu-latest

    env:
      KUBE_SERVER: https://k8s.siandji.com
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

    steps:
      - name: Vérifier l'environnement
        run: echo "Pipeline Kubernetes démarré"

      - name: Installer kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Vérifier la version de kubectl
        run: kubectl version --client
          
      - name: Lister les nodes Kubernetes
        run: |
          kubectl get nodes \
            --token="$KUBE_TOKEN" \
            --insecure-skip-tls-verify \
            --server="$KUBE_SERVER"
