name: Deploy nginx Pod via SSH Tunnel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.keyrsa }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add remote host to known_hosts
        run: ssh-keyscan -H 10.17.3.6 >> ~/.ssh/known_hosts

      - name: Start SSH tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -N -L 6443:10.17.3.6:6443 k8s@10.17.3.6 &
          sleep 5

      - name: Deploy nginx pod
        run: |
          kubectl --server=https://localhost:6443 --insecure-skip-tls-verify run nginx-pod --image=nginx
          kubectl --server=https://localhost:6443 --insecure-skip-tls-verify get pods
